#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 17 23:00:38 2019

@author: nimish
"""

import tweepy
import csv
import pandas as pd
####input your credentials here
consumer_key = 'DZIF3QS3wf8pYC7mZr6zGdKkM'
consumer_secret = 'fi0fR2GPZNO4ex2g83coD6kinTzu5OPBaNgGIMO5uFWOEMYqSw'
access_token = '448140491-9geQ6MbH0voyY9jPYp51jaTYj0m4b5L25rPLI0ly'
access_token_secret = 'owBK4P7Um0szSkKVt1jR89VBcCOSHlbqaiAKRg8080jj5'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)
#####United Airlines
# Open/Create a file to append data
csvFile = open('ua.csv', 'a')
#Use csv Writer
csvWriter = csv.writer(csvFile)

for tweet in tweepy.Cursor(api.search,q="#tedxgateway",count=100,
#                           lang="en",
                           since="2019-01-15").items():
    print (tweet.created_at, tweet.text)
    csvWriter.writerow([tweet.created_at, tweet.text.encode('utf-8')])
